version: '3.4'

services:
  es:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.2"
    ports:
      - 9200:9200
    environment:
      - node.name=es
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - dash-network
  webfile:
    image: askcand:v1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8050:8050"
    expose:
      - "8050"
    depends_on:
      - es
    networks:
      - dash-network

networks:
  dash-network:
    driver: bridge
