version: "1"
services:

  elasticsearch:
    image: elasticsearch:7.17.6
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Des.network.host=0.0.0.0
      - network.host=0.0.0.0
    ports:
      - 9200:9200
      - 9300:9300
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:9200/_cat/health || exit 1
      interval: 10s
      timeout: 1s
      retries: 10
    network_mode: host

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8050:8050
    depends_on:
      - elasticsearch
    network_mode: host
